name: freelance_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # internationalization, localization and other formatter ( null safety )
  intl: ^0.17.0

  # state management ( null safety )
  stacked: ^2.1.0

  # http request handling ( null safety )
  dio: ^4.0.0

  # cupertinoIcons class for iOS style icons ( null safety )
  cupertino_icons: ^1.0.2

  # local repo packages ( null safety )
  basic_services: # bundle of services
    git:
      url: https://github.com/Hendi-arch/basic_services.git
      ref: 42ac19bb3a087d3f14a6fa3d5515e98906982043

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  stacked_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
